/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HtmlViewerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/view/HtmlView.ts
var import_obsidian = require("obsidian");

// src/ipc/IpcBridge.ts
function getClickInterceptorScript() {
  return `
(function() {
  document.addEventListener('click', function(e) {
    var anchor = e.target.closest ? e.target.closest('a') : null;
    if (!anchor) return;
    var href = anchor.getAttribute('href');
    if (!href) return;
    if (href.startsWith('#')) return;

    var lowerHref = href.toLowerCase();
    if (lowerHref.startsWith('http://') || lowerHref.startsWith('https://') || lowerHref.startsWith('mailto:')) {
      e.preventDefault();
      window.parent.postMessage({ type: 'obsidian-open-external', url: href }, '*');
    } else {
      e.preventDefault();
      window.parent.postMessage({ type: 'obsidian-navigate', linkText: href }, '*');
    }
  }, true);
})();
`;
}
var IPC_SCRIPT_TEMPLATE = getClickInterceptorScript();
var IpcBridge = class {
  constructor(app, getSourcePath) {
    this.messageHandler = null;
    this.iframeEl = null;
    this.app = app;
    this.getSourcePath = getSourcePath;
  }
  setIframe(iframeEl) {
    this.iframeEl = iframeEl;
  }
  attach(iframeEl) {
    if (iframeEl !== void 0) {
      this.iframeEl = iframeEl;
    }
    if (this.messageHandler)
      return;
    this.messageHandler = (event) => {
      try {
        const data = event.data;
        if (!data || typeof data !== "object")
          return;
        if (!this.iframeEl || !this.iframeEl.contentWindow || event.source !== this.iframeEl.contentWindow) {
          return;
        }
        if (data.type === "obsidian-navigate") {
          if (typeof data.linkText !== "string")
            return;
          let sanitizedLinkText = data.linkText;
          try {
            sanitizedLinkText = decodeURIComponent(sanitizedLinkText);
          } catch (e) {
          }
          sanitizedLinkText = sanitizedLinkText.replace(/%2f/gi, "/").replace(/%5c/gi, "\\");
          let prev;
          do {
            prev = sanitizedLinkText;
            sanitizedLinkText = sanitizedLinkText.replace(/\.\./g, "").replace(/[/\\]+/g, "/");
          } while (sanitizedLinkText !== prev);
          sanitizedLinkText = sanitizedLinkText.replace(/^\/+/, "");
          const sourcePath = this.getSourcePath();
          if (this.app && this.app.workspace && typeof this.app.workspace.openLinkText === "function") {
            void this.app.workspace.openLinkText(sanitizedLinkText, sourcePath, false);
          }
        } else if (data.type === "obsidian-open-external") {
          if (typeof data.url !== "string")
            return;
          const trimmedUrl = data.url.trim();
          const lowerUrl = trimmedUrl.toLowerCase();
          if (lowerUrl.startsWith("http://") || lowerUrl.startsWith("https://") || lowerUrl.startsWith("mailto:")) {
            window.open(trimmedUrl, "_blank");
          }
        }
      } catch (e) {
      }
    };
    window.addEventListener("message", this.messageHandler);
  }
  detach() {
    if (this.messageHandler) {
      window.removeEventListener("message", this.messageHandler);
      this.messageHandler = null;
    }
  }
};

// src/engine/HtmlAssetResolver.ts
function isExternalOrSpecialUrl(url) {
  if (!url)
    return true;
  const trimmed = url.trim();
  if (trimmed.startsWith("#") || trimmed.startsWith("?"))
    return true;
  if (/^[a-z][a-z0-9+.-]*:/i.test(trimmed) || trimmed.startsWith("//")) {
    return true;
  }
  return false;
}
function splitUrl(url) {
  const qIdx = url.indexOf("?");
  const hIdx = url.indexOf("#");
  let splitIdx = -1;
  if (qIdx !== -1 && hIdx !== -1) {
    splitIdx = Math.min(qIdx, hIdx);
  } else if (qIdx !== -1) {
    splitIdx = qIdx;
  } else if (hIdx !== -1) {
    splitIdx = hIdx;
  }
  if (splitIdx !== -1) {
    return {
      basePath: url.slice(0, splitIdx),
      queryHashSuffix: url.slice(splitIdx)
    };
  }
  return { basePath: url, queryHashSuffix: "" };
}
function normalizeVaultPath(baseFolder, relativePath) {
  if (relativePath.startsWith("/")) {
    const relParts2 = relativePath.split("/");
    const stack2 = [];
    for (const part of relParts2) {
      if (part === "" || part === ".")
        continue;
      if (part === "..") {
        if (stack2.length > 0)
          stack2.pop();
      } else {
        stack2.push(part);
      }
    }
    return stack2.join("/");
  }
  const baseParts = baseFolder ? baseFolder.split("/").filter((p) => p.length > 0 && p !== ".") : [];
  const relParts = relativePath.split("/");
  const stack = [...baseParts];
  for (const part of relParts) {
    if (part === "" || part === ".")
      continue;
    if (part === "..") {
      if (stack.length > 0) {
        stack.pop();
      }
    } else {
      stack.push(part);
    }
  }
  return stack.join("/");
}
function processSrcset(srcsetVal, currentFileFolderPath, getResourcePathFn, assetPaths, resolvedUris) {
  const candidates = srcsetVal.split(",");
  const processedCandidates = candidates.map((candidate) => {
    const trimmed = candidate.trim();
    if (!trimmed)
      return candidate;
    const match = trimmed.match(/^(\S+)(\s+[\s\S]+)?$/);
    if (!match)
      return candidate;
    const rawUrl = match[1];
    const descriptor = match[2] || "";
    if (isExternalOrSpecialUrl(rawUrl)) {
      return candidate;
    }
    const { basePath, queryHashSuffix } = splitUrl(rawUrl);
    const vaultPath = normalizeVaultPath(currentFileFolderPath, basePath);
    assetPaths.push(vaultPath);
    const resolvedUri = getResourcePathFn(vaultPath) + queryHashSuffix;
    if (resolvedUris) {
      resolvedUris.push(resolvedUri);
    }
    return resolvedUri + descriptor;
  });
  return processedCandidates.join(", ");
}
function extractCspSource(uri) {
  if (!uri)
    return null;
  const match = uri.match(/^([a-z][a-z0-9+.-]*:\/\/[^/]+)/i);
  if (match) {
    return match[1];
  }
  const schemeMatch = uri.match(/^([a-z][a-z0-9+.-]*:)/i);
  if (schemeMatch) {
    return schemeMatch[1];
  }
  return null;
}
function resolveCssUrls(cssContent, cssFilePath, getResourcePathFn) {
  return cssContent.replace(/url\(\s*['"]?([^'")\s]+)['"]?\s*\)/g, (match, relUrl) => {
    if (isExternalOrSpecialUrl(relUrl)) {
      return match;
    }
    const cssFolder = cssFilePath.includes("/") ? cssFilePath.substring(0, cssFilePath.lastIndexOf("/")) : "";
    const vaultPath = normalizeVaultPath(cssFolder, relUrl);
    const resolvedUri = getResourcePathFn(vaultPath);
    return `url('${resolvedUri}')`;
  });
}
async function resolveHtmlAssets(options) {
  const { rawHtml, currentFileFolderPath, getResourcePathFn, readVaultFileFn } = options;
  const assetPaths = [];
  const resolvedUris = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(rawHtml, "text/html");
  const processSingleAttribute = (el, attrName) => {
    const attrVal = el.getAttribute(attrName);
    if (attrVal && !isExternalOrSpecialUrl(attrVal)) {
      const { basePath, queryHashSuffix } = splitUrl(attrVal);
      const vaultPath = normalizeVaultPath(currentFileFolderPath, basePath);
      assetPaths.push(vaultPath);
      const resolvedUri = getResourcePathFn(vaultPath) + queryHashSuffix;
      resolvedUris.push(resolvedUri);
      el.setAttribute(attrName, resolvedUri);
    }
  };
  const processSrcsetAttribute = (el) => {
    const attrVal = el.getAttribute("srcset");
    if (attrVal) {
      const transformedSrcset = processSrcset(attrVal, currentFileFolderPath, getResourcePathFn, assetPaths, resolvedUris);
      el.setAttribute("srcset", transformedSrcset);
    }
  };
  const linkElements = Array.from(doc.querySelectorAll("link[href]"));
  for (const node of linkElements) {
    const rel = node.getAttribute("rel");
    const href = node.getAttribute("href");
    if (rel === "stylesheet" && href && !isExternalOrSpecialUrl(href) && readVaultFileFn) {
      const { basePath } = splitUrl(href);
      const vaultPath = normalizeVaultPath(currentFileFolderPath, basePath);
      assetPaths.push(vaultPath);
      try {
        const cssContent = await readVaultFileFn(vaultPath);
        const resolvedCss = resolveCssUrls(cssContent, vaultPath, getResourcePathFn);
        const styleEl = doc.createElement("style");
        styleEl.textContent = resolvedCss;
        if (node.parentNode) {
          node.parentNode.replaceChild(styleEl, node);
        }
        console.log(`resolveHtmlAssets: Inlined stylesheet ${vaultPath}`);
      } catch (e) {
        console.error(`resolveHtmlAssets: Failed to inline stylesheet ${vaultPath}, falling back:`, e);
        processSingleAttribute(node, "href");
      }
    } else {
      processSingleAttribute(node, "href");
    }
  }
  doc.querySelectorAll("script[src]").forEach((node) => processSingleAttribute(node, "src"));
  doc.querySelectorAll("img").forEach((node) => {
    if (node.hasAttribute("src"))
      processSingleAttribute(node, "src");
    if (node.hasAttribute("srcset"))
      processSrcsetAttribute(node);
  });
  doc.querySelectorAll("video").forEach((node) => {
    if (node.hasAttribute("src"))
      processSingleAttribute(node, "src");
    if (node.hasAttribute("poster"))
      processSingleAttribute(node, "poster");
  });
  doc.querySelectorAll("audio").forEach((node) => {
    if (node.hasAttribute("src"))
      processSingleAttribute(node, "src");
  });
  doc.querySelectorAll("source").forEach((node) => {
    if (node.hasAttribute("src"))
      processSingleAttribute(node, "src");
    if (node.hasAttribute("srcset"))
      processSrcsetAttribute(node);
  });
  doc.querySelectorAll("iframe").forEach((node) => {
    if (node.hasAttribute("src"))
      processSingleAttribute(node, "src");
  });
  let head = doc.querySelector("head");
  if (!head) {
    head = doc.createElement("head");
    if (doc.documentElement) {
      doc.documentElement.insertBefore(head, doc.documentElement.firstChild);
    }
  }
  const allowedSources = /* @__PURE__ */ new Set(["app:", "app://*", "file:", "data:", "blob:"]);
  for (const uri of resolvedUris) {
    const src = extractCspSource(uri);
    if (src) {
      allowedSources.add(src);
    }
  }
  const cspMetas = Array.from(doc.querySelectorAll("meta")).filter((meta) => {
    const httpEquiv = meta.getAttribute("http-equiv");
    return httpEquiv && httpEquiv.trim().toLowerCase() === "content-security-policy";
  });
  console.log("resolveHtmlAssets: Found total meta tags:", doc.querySelectorAll("meta").length);
  Array.from(doc.querySelectorAll("meta")).forEach((m, idx) => {
    console.log(`resolveHtmlAssets: Meta #${idx}: http-equiv="${m.getAttribute("http-equiv")}", content="${m.getAttribute("content")}"`);
  });
  if (cspMetas.length === 0) {
    const newCspMeta = doc.createElement("meta");
    newCspMeta.setAttribute("http-equiv", "Content-Security-Policy");
    newCspMeta.setAttribute("content", "default-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';");
    head.insertBefore(newCspMeta, head.firstChild);
    cspMetas.push(newCspMeta);
    console.log("resolveHtmlAssets: Injected new CSP meta tag");
  }
  cspMetas.forEach((meta, idx) => {
    const cspContent = meta.getAttribute("content") || "";
    const directiveMap = /* @__PURE__ */ new Map();
    const directives = cspContent.split(";").map((d) => d.trim()).filter((d) => d.length > 0);
    for (const dir of directives) {
      const parts = dir.split(/\s+/);
      const name = parts[0].toLowerCase();
      const values = parts.slice(1);
      directiveMap.set(name, new Set(values));
    }
    if (!directiveMap.has("default-src")) {
      directiveMap.set("default-src", /* @__PURE__ */ new Set(["'self'"]));
    }
    const targetDirectives = ["default-src", "script-src", "style-src", "img-src", "media-src"];
    for (const target of targetDirectives) {
      if (directiveMap.has(target)) {
        const values = directiveMap.get(target);
        for (const src of allowedSources) {
          values.add(src);
        }
      }
    }
    const updatedDirectives = [];
    for (const [name, values] of directiveMap.entries()) {
      updatedDirectives.push(`${name} ${Array.from(values).join(" ")}`);
    }
    const finalContent = updatedDirectives.join("; ") + ";";
    console.log(`resolveHtmlAssets: Updating CSP Meta #${idx} content to:`, finalContent);
    meta.setAttribute("content", finalContent);
  });
  const hasDoctype = Boolean(doc.doctype) || /^\s*<!DOCTYPE\s+html/i.test(rawHtml);
  let transformedHtml = doc.documentElement ? doc.documentElement.outerHTML : doc.body.innerHTML;
  if (hasDoctype && !/^\s*<!DOCTYPE\s+html/i.test(transformedHtml)) {
    transformedHtml = "<!DOCTYPE html>\n" + transformedHtml;
  }
  const scriptContent = getClickInterceptorScript();
  const scriptTag = `<script>${scriptContent}<\/script>`;
  if (transformedHtml.match(/<\/head>/i)) {
    transformedHtml = transformedHtml.replace(/<\/head>/i, `${scriptTag}</head>`);
  } else if (transformedHtml.match(/<body>/i)) {
    transformedHtml = transformedHtml.replace(/<body>/i, `<body>${scriptTag}`);
  } else {
    transformedHtml = scriptTag + transformedHtml;
  }
  return {
    transformedHtml,
    assetPaths: Array.from(new Set(assetPaths))
  };
}

// src/watcher/VaultWatcher.ts
var VaultWatcher = class {
  constructor(vault, getCurrentFilePath, onReload) {
    this.trackedDependencies = /* @__PURE__ */ new Set();
    this.eventRef = null;
    // Global & Multi-view dependency maps
    this.viewsByHtmlPath = /* @__PURE__ */ new Map();
    this.dependenciesByHtmlPath = /* @__PURE__ */ new Map();
    this.vault = vault || null;
    this.getCurrentFilePath = getCurrentFilePath;
    this.onReload = onReload;
  }
  normalizePath(path) {
    if (!path)
      return "";
    let normalized = path.replace(/\\/g, "/");
    while (normalized.startsWith("./")) {
      normalized = normalized.substring(2);
    }
    const parts = normalized.split("/");
    const stack = [];
    for (const part of parts) {
      if (part === "" || part === ".") {
        continue;
      }
      if (part === "..") {
        if (stack.length > 0) {
          stack.pop();
        }
      } else {
        stack.push(part);
      }
    }
    return stack.join("/");
  }
  setDependencies(dependencies) {
    this.trackedDependencies = new Set(dependencies.map((d) => this.normalizePath(d)));
    if (this.getCurrentFilePath) {
      const currentPath = this.getCurrentFilePath();
      if (currentPath) {
        this.updateDependencies(currentPath, dependencies);
      }
    }
  }
  registerView(htmlPath, callback, dependencies = []) {
    if (!htmlPath)
      return;
    const normHtmlPath = this.normalizePath(htmlPath);
    if (!this.viewsByHtmlPath.has(normHtmlPath)) {
      this.viewsByHtmlPath.set(normHtmlPath, /* @__PURE__ */ new Set());
    }
    this.viewsByHtmlPath.get(normHtmlPath).add(callback);
    this.updateDependencies(normHtmlPath, dependencies, callback);
  }
  updateDependencies(htmlPath, dependencies, callback) {
    if (!htmlPath)
      return;
    const normHtmlPath = this.normalizePath(htmlPath);
    const normDeps = new Set(dependencies.map((d) => this.normalizePath(d)));
    if (!this.dependenciesByHtmlPath.has(normHtmlPath)) {
      this.dependenciesByHtmlPath.set(normHtmlPath, /* @__PURE__ */ new Map());
    }
    const viewMap = this.dependenciesByHtmlPath.get(normHtmlPath);
    let targetCb = callback || null;
    if (!targetCb && this.onReload && this.getCurrentFilePath) {
      const current = this.getCurrentFilePath();
      if (current && this.normalizePath(current) === normHtmlPath) {
        targetCb = this.onReload;
      }
    }
    if (targetCb) {
      viewMap.set(targetCb, normDeps);
    } else {
      const existingCbs = this.viewsByHtmlPath.get(normHtmlPath);
      if (existingCbs && existingCbs.size > 0) {
        existingCbs.forEach((cb) => viewMap.set(cb, normDeps));
      } else {
        viewMap.set(null, normDeps);
      }
    }
  }
  unregisterView(htmlPath, callback) {
    if (!htmlPath)
      return;
    const normHtmlPath = this.normalizePath(htmlPath);
    const callbacks = this.viewsByHtmlPath.get(normHtmlPath);
    const viewMap = this.dependenciesByHtmlPath.get(normHtmlPath);
    if (callback) {
      if (callbacks) {
        callbacks.delete(callback);
      }
      if (viewMap) {
        viewMap.delete(callback);
      }
    } else {
      if (viewMap) {
        viewMap.delete(null);
        if (this.onReload) {
          viewMap.delete(this.onReload);
        }
      }
      if (callbacks && this.onReload) {
        callbacks.delete(this.onReload);
      }
    }
    if (callbacks && callbacks.size === 0) {
      this.viewsByHtmlPath.delete(normHtmlPath);
      this.dependenciesByHtmlPath.delete(normHtmlPath);
    } else if (viewMap && viewMap.size === 0 && (!callbacks || callbacks.size === 0)) {
      this.dependenciesByHtmlPath.delete(normHtmlPath);
    }
  }
  getDependencies(htmlPath) {
    const normHtmlPath = this.normalizePath(htmlPath);
    const viewMap = this.dependenciesByHtmlPath.get(normHtmlPath);
    if (viewMap) {
      const combined = /* @__PURE__ */ new Set();
      for (const assetSet of viewMap.values()) {
        assetSet.forEach((asset) => combined.add(asset));
      }
      if (combined.size > 0) {
        return Array.from(combined);
      }
    }
    return Array.from(this.trackedDependencies);
  }
  register() {
    const vault = this.vault;
    if (this.eventRef || !vault || typeof vault.on !== "function")
      return;
    this.eventRef = vault.on("modify", (file) => {
      if (!file || !file.path)
        return;
      const modifiedPath = this.normalizePath(file.path);
      const triggeredCallbacks = /* @__PURE__ */ new Set();
      if (this.getCurrentFilePath && this.onReload) {
        const rawCurrent = this.getCurrentFilePath();
        if (rawCurrent) {
          const currentPath = this.normalizePath(rawCurrent);
          if (modifiedPath === currentPath || this.trackedDependencies.has(modifiedPath)) {
            triggeredCallbacks.add(this.onReload);
          }
        }
      }
      const directSubscribers = this.viewsByHtmlPath.get(modifiedPath);
      if (directSubscribers) {
        directSubscribers.forEach((cb) => triggeredCallbacks.add(cb));
      }
      for (const [htmlPath, viewMap] of this.dependenciesByHtmlPath.entries()) {
        const activeSubscribers = this.viewsByHtmlPath.get(htmlPath);
        for (const [cb, assets] of viewMap.entries()) {
          if (assets.has(modifiedPath)) {
            if (cb) {
              if (cb === this.onReload || activeSubscribers && activeSubscribers.has(cb)) {
                triggeredCallbacks.add(cb);
              }
            } else if (activeSubscribers) {
              activeSubscribers.forEach((c) => triggeredCallbacks.add(c));
            }
          }
        }
      }
      triggeredCallbacks.forEach((cb) => {
        try {
          cb();
        } catch (err) {
          console.error("Error executing reload callback in VaultWatcher:", err);
        }
      });
    });
  }
  unregister() {
    const vault = this.vault;
    if (this.eventRef && vault && typeof vault.offref === "function") {
      vault.offref(this.eventRef);
      this.eventRef = null;
    }
  }
};

// src/view/HtmlView.ts
var VIEW_TYPE_HTML = "html-viewer-view";
var HtmlView = class extends import_obsidian.FileView {
  constructor(leaf, vaultWatcher) {
    super(leaf);
    this.mode = "preview";
    this.renderId = 0;
    this.actionsRegistered = false;
    this.isWatcherShared = false;
    this.ipcBridge = new IpcBridge(this.app, () => this.file ? this.file.path : "");
    this.reloadCallback = () => {
      void this.renderView();
    };
    if (vaultWatcher) {
      this.vaultWatcher = vaultWatcher;
      this.isWatcherShared = true;
    } else {
      this.vaultWatcher = new VaultWatcher(
        this.app ? this.app.vault : null,
        () => this.file ? this.file.path : null,
        this.reloadCallback
      );
      this.isWatcherShared = false;
    }
  }
  getViewType() {
    return VIEW_TYPE_HTML;
  }
  getDisplayText() {
    return this.file ? this.file.basename : "HTML Viewer";
  }
  async onLoadFile(file) {
    this.file = file;
    const basePromise = super.onLoadFile(file);
    this.vaultWatcher.registerView(file.path, this.reloadCallback);
    const renderPromise = this.renderView();
    await basePromise;
    await renderPromise;
  }
  async onUnloadFile(file) {
    this.vaultWatcher.unregisterView(file.path, this.reloadCallback);
    await super.onUnloadFile(file);
  }
  async onOpen() {
    this.ipcBridge.attach();
    if (this.file) {
      this.vaultWatcher.registerView(this.file.path, this.reloadCallback);
    }
    if (!this.actionsRegistered) {
      this.actionsRegistered = true;
      this.addAction("code", "Toggle source code", () => {
        this.mode = this.mode === "preview" ? "source" : "preview";
        void this.renderView();
      });
      this.addAction("refresh-cw", "Reload", () => {
        void this.renderView();
      });
    }
  }
  async onClose() {
    this.ipcBridge.detach();
    if (this.file) {
      this.vaultWatcher.unregisterView(this.file.path, this.reloadCallback);
    }
    if (!this.isWatcherShared) {
      this.vaultWatcher.unregister();
    }
    this.actionsRegistered = false;
    await super.onClose();
  }
  async renderView() {
    if (!this.file)
      return;
    const container = this.contentEl;
    container.empty();
    container.addClass("html-viewer-container");
    try {
      const id = ++this.renderId;
      const rawHtml = await this.app.vault.read(this.file);
      if (id !== this.renderId)
        return;
      if (!rawHtml || rawHtml.replace(/\0/g, "").trim() === "") {
        throw new Error("HTML file is empty");
      }
      const parser = new DOMParser();
      const doc = parser.parseFromString(rawHtml, "text/html");
      const parserError = doc.querySelector("parsererror");
      if (parserError) {
        throw new Error("Malformed or invalid HTML structure");
      }
      const currentFolder = this.file.parent ? this.file.parent.path : "";
      const result = await resolveHtmlAssets({
        rawHtml,
        currentFileFolderPath: currentFolder,
        getResourcePathFn: (path) => {
          const tfile = this.app.vault.getAbstractFileByPath(path);
          if (tfile instanceof import_obsidian.TFile) {
            return this.app.vault.getResourcePath(tfile);
          }
          return path;
        },
        readVaultFileFn: async (path) => {
          const tfile = this.app.vault.getAbstractFileByPath(path);
          if (tfile instanceof import_obsidian.TFile) {
            return await this.app.vault.read(tfile);
          }
          throw new Error(`File not found: ${path}`);
        }
      });
      this.vaultWatcher.setDependencies(result.assetPaths);
      this.vaultWatcher.updateDependencies(this.file.path, result.assetPaths, this.reloadCallback);
      if (this.mode === "preview") {
        const iframeEl = container.createEl("iframe", {
          cls: "html-viewer-iframe",
          attr: { sandbox: "allow-scripts allow-forms allow-same-origin allow-modals" }
        });
        iframeEl.srcdoc = result.transformedHtml;
        this.ipcBridge.setIframe(iframeEl);
      } else {
        this.ipcBridge.setIframe(null);
        const sourceEl = container.createEl("pre", { cls: "html-viewer-source-container" });
        sourceEl.textContent = rawHtml;
      }
    } catch (err) {
      this.ipcBridge.setIframe(null);
      container.empty();
      container.addClass("html-viewer-container");
      const errorContainer = container.createDiv({ cls: "html-viewer-error-container" });
      const card = errorContainer.createDiv({ cls: "html-viewer-error-card" });
      const header = card.createDiv({ cls: "html-viewer-error-header" });
      header.createDiv({ cls: "html-viewer-error-title", text: "Error Loading HTML File" });
      const errorMessage = err instanceof Error ? err.message : String(err);
      card.createDiv({ cls: "html-viewer-error-message", text: errorMessage });
    }
  }
};

// src/main.ts
var HtmlViewerPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    this.vaultWatcher = new VaultWatcher(this.app.vault);
    this.vaultWatcher.register();
    this.registerView(
      VIEW_TYPE_HTML,
      (leaf) => new HtmlView(leaf, this.vaultWatcher)
    );
    try {
      this.registerExtensions(["html"], VIEW_TYPE_HTML);
    } catch (e) {
      console.warn("HTML extension already registered or conflict:", e);
    }
  }
  onunload() {
    if (this.vaultWatcher) {
      this.vaultWatcher.unregister();
    }
  }
};

/* nosourcemap */